Update patch set 2
Patch Set 2:

> java.lang.LinkageError: loader constraint violation: loader
 > (instance of org/eclipse/osgi/internal/loader/EquinoxClassLoader)
 > previously initiated loading for a different type with name
 > "org/apache/karaf/bundle/core/BundleService"

in installFeature(org.opendaylight.odlparent.featuretest.SingleFeatureTest)[repoUrl: file:/w/workspace/aaa-verify-carbon-mvn33-openjdk8/features/shiro/features4-aaa-shiro/target/feature/feature.xml, Feature: odl-aaa-shiro 0.5.0.SNAPSHOT]

 > is it possible that we somehow mixed up having both Karaf here

NB that e.g. aaa/features/authn/ ("OpenDaylight :: AAA :: Authentication - NO CLUSTER") passed, that's Karaf 3, so is features/shiro/features4-aaa-shiro the first Karaf 4 feature in AAA we've migrated that trips over due to this?

Patch-set: 2