Update patch set 5
Patch Set 5: Code-Review+1

I tested this with all the configs enabled.

JDBC Realm failed with:

Caused by: org.apache.shiro.util.UnknownClassException: Unable to load class named [com.mysql.jdbc.Driver] from the thread context, current, or system/application ClassLoaders.  All heuristics have been exhausted.  Class could not be found.

So we're missing the libs but that was an issue prior to this patch. Perhaps the pre-requirement is to install those libs separately.

The LDAP Realm fails as well:

2018-03-20T15:57:49,446 | ERROR | Blueprint Extender: 3 | EnvironmentLoader                | 160 - org.apache.shiro.web - 1.3.2 | Shiro environment initialization failed
org.apache.shiro.config.ConfigurationException: Property 'searchBase' does not exist for object of type org.opendaylight.aaa.shiro.realm.ODLJndiLdapRealmAuthNOnly.

But that's a separate config issue and existed prior as well.

Patch-set: 5
Reviewer: Gerrit User 1842 <1842@7fc14799-209e-464c-9743-7a06c2c21a81>
Label: Code-Review=+1