Update patch set 6
Patch Set 6:

This still fails for me with:

installFeature(org.opendaylight.odlparent.featuretest.SingleFeatureTest)[repoUrl: file:/home/moriarty/src/opendaylight/aaa/features/authn/features4-aaa/target/feature/feature.xml, Feature: odl-aaa-cli 0.5.0.SNAPSHOT]  Time elapsed: 23.691 sec  <<< ERROR!
org.ops4j.pax.exam.WrappedTestContainerException: [installFeature(org.opendaylight.odlparent.featuretest.SingleFeatureTest): Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=odl-aaa-cli; type=karaf.feature; version="[0.5.0.SNAPSHOT,0.5.0.SNA
PSHOT]"; filter:="(&(osgi.identity=odl-aaa-cli)(type=karaf.feature)(version>=0.5.0.SNAPSHOT)(version<=0.5.0.SNAPSHOT))" [caused by: Unable to resolve odl-aaa-cli/0.5.0.SNAPSHOT: missing requirement [odl-aaa-cli/0.5.0.SNAPSHOT] osgi.identity; osgi.identity=org.opendaylight
.aaa.cli4; type=osgi.bundle; version="[0.5.0.SNAPSHOT,0.5.0.SNAPSHOT]"; resolution:=mandatory [caused by: Unable to resolve org.opendaylight.aaa.cli4/0.5.0.SNAPSHOT: missing requirement [org.opendaylight.aaa.cli4/0.5.0.SNAPSHOT] osgi.service; effective:=active; filter:="(
objectClass=org.opendaylight.aaa.cert.api.ICertificateManager)"]]]

Patch-set: 6
Label: Verified=0