Fix: Use mvn version 3.8.3
The version of mvn does not match what is required in pom file.

Error:  Detected Maven Version: 3.8.2 is not in the allowed
range [3.8.3,).

Change-Id: Ie1133036b5ceb235cf7ce712ef762b70b3be21be
Signed-off-by: Anil Belur <abelur@linuxfoundation.org>