Update patch set 1
Patch Set 1:

> I'm not really familiar with python. These changes are needed for
 > python 3 but are they backwards compatible with python 2 etc?

Yes, it is compatible with any odl python version.

[yangyi@localhost aaa]$ python --version
Python 2.7.5
[yangyi@localhost aaa]$ git log
commit 321f12e797233830e8875d437bd84f11d7edecd2
Author: Yi Yang <yangyi01@inspur.com>
Date:   Sun Jan 27 21:50:35 2019 -0500

    Fix idmtool print error in case of using python3

    In Ubuntu 16.04, python3 is default python version, but idmtool
    is still using non-strict print syntax, so it won't work if we
    use python3, here is error information.

    vagrant@odl:~$ python3 ./idmtool.py.orig
    File "./idmtool.py.orig", line 143
    print ''
    ^
    SyntaxError: Missing parentheses in call to 'print'

    In python3, print must use parentheses to embrace all the arguments.

    Change-Id: Icec4c9c0225cae4c62e2189af9702789906d5e4f
    JIRA: AAA-183
    Signed-off-by: Yi Yang <yangyi01@inspur.com>

[yangyi@localhost aaa]$ python ./aaa-shiro/impl/src/main/resources/idmtool.py -h
usage: idmtool [-h] [--target-host TARGET_HOST] [-k]
               user
               {list-users,add-user,change-password,delete-user,list-domains,list-roles,add-role,delete-role,add-grant,get-grants,delete-grant,get-oauth2-token,change-jolokia-password}
               ...

positional arguments:
  user                  username for ODL node
  {list-users,add-user,change-password,delete-user,list-domains,list-roles,add-role,delete-role,add-grant,get-grants,delete-grant,get-oauth2-token,change-jolokia-password}
                        sub-command help
    list-users          list all users
    add-user            add a user
    change-password     change a password
    delete-user         delete a user
    list-domains        list all domains
    list-roles          list all roles
    add-role            add a role
    delete-role         delete a role
    add-grant           add a grant
    get-grants          get grants for userid on sdn
    delete-grant        delete a grant
    get-oauth2-token    get an OAuth2 token
    change-jolokia-password
                        change the jolokia specific password

optional arguments:
  -h, --help            show this help message and exit
  --target-host TARGET_HOST
                        target host url in form protocol://host:port
  -k, --insecure        disable HTTPS certificate verification
[yangyi@localhost aaa]$ python ./aaa-shiro/impl/src/main/resources/idmtool.py
usage: idmtool [-h] [--target-host TARGET_HOST] [-k]
               user
               {list-users,add-user,change-password,delete-user,list-domains,list-roles,add-role,delete-role,add-grant,get-grants,delete-grant,get-oauth2-token,change-jolokia-password}
               ...
idmtool: error: too few arguments
[yangyi@localhost aaa]$

Patch-set: 1
Reviewer: Gerrit User 8310 <8310@7fc14799-209e-464c-9743-7a06c2c21a81>
Label: Verified=0