Fix idmtool print error in case of using python3
In Ubuntu 16.04, python3 is default python version, but idmtool
is still using non-strict print syntax, so it won't work if we
use python3, here is error information.

vagrant@odl:~$ python3 ./idmtool.py.orig
File "./idmtool.py.orig", line 143
print ''
^
SyntaxError: Missing parentheses in call to 'print'

In python3, print must use parentheses to embrace all the arguments.

Change-Id: Icec4c9c0225cae4c62e2189af9702789906d5e4f
JIRA: AAA-183
Signed-off-by: Yi Yang <yangyi01@inspur.com>