Update patch set 6
Patch Set 6:

This fails aaa-cli-jar's failsafe due to:

Aborting due to NoClassDefFoundError (use -X to see full stack trace): org/h2/JdbcDriverBackwardsCompat

Patch-set: 6
Label: Verified=0