move jersey-guava dep from odl-aaa-web to servlet-jersey2
so that "component" (non-IT) tests depending on servlet-jersey2 get it
as well, without having to (guess the version and) redundantly
re-declare this dependency again; see TBD, to avoid/solve:

Caused by: java.lang.NoSuchMethodError:
jersey.repackaged.com.google.common.collect.Iterables.concat(Ljava/lang/Iterable;Ljava/lang/Iterable;)Ljava/lang/Iterable;
	at org.glassfish.jersey.server.internal.ConfigHelper.getContainerLifecycleListener(ConfigHelper.java:86)

Nothing changes under OSGi because the odl-aaa-web Karaf feature remains
unchanged, it just gets jersey-guava via servlet-jersey2 instead now.

This needs to wait for https://git.opendaylight.org/gerrit/#/c/72408/
(AKA Change-Id: Ibb08b0ebff778f842e20b8ef7e10e17126397534), because even
though it would be transitively inherited from aaa.web:servlet-jersey2;
it will ultimately be the wrong old version, because odlparent's
dependendencyManagement is stronger than the transitive dependency.  We
could repeat the dependency with the version here, but projects such as
neutron/integration/test-standalone would still have to repeat it anyway
again (for the same reason), so that's pointless.

Change-Id: Ib7d5d1aaa7850919d7e91bd53dfb54db0a585c13
Signed-off-by: Michael Vorburger <vorburger@redhat.com>